apiVersion: v1
kind: Service
metadata:
  name: forex-service
spec:
  selector:
    app: forex
  ports:
  - protocol: "TCP"
    port: 9999
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex
spec:
  selector:
    matchLabels:
      app: forex
  replicas: 4
  template:
    metadata:
      labels:
        app: forex
    spec:
      containers:
      - name: forex
        image: newdelthis/forex:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000